"use client";

import { useEffect, useState } from "react";
import { ColumnDef } from "@tanstack/react-table";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { DataTable } from "../DataTable";
import { FormDialog } from "../FormDialog";
import { userAPI, User } from "@/app/admin/lib/api";

export function UsersManager() {
  const [users, setUsers] = useState<User[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [currentPage, setCurrentPage] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [searchQuery, setSearchQuery] = useState("");
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingUser, setEditingUser] = useState<User | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formData, setFormData] = useState<User>({
    uid: "",
    email: "",
    pwHash: "",
    roles: "ROLE_USER",
  }); // Note: uid will be auto-generated by backend

  const loadUsers = async (page = 0, search = "") => {
    try {
      setIsLoading(true);
      console.log("📥 Loading users from page:", page, "search:", search);
      const response = await userAPI.getAll(page, 25, search);
      console.log("✅ Users loaded:", {
        page,
        count: response.content.length,
        responseNumber: response.number,
        totalPages: response.totalPages,
        fullResponse: response,
      });
      setUsers(response.content);
      // Spring returns 'number' for current page, not 'currentPage'
      setCurrentPage(response.number ?? page);
      setTotalPages(response.totalPages);
    } catch (error) {
      console.error("❌ Error loading users:", error);
      toast.error(
        `Failed to load users: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    // Only load on client side after component mounts
    if (typeof window !== "undefined") {
      loadUsers(currentPage, searchQuery);
    }
  }, []);

  const handleSearch = (query: string) => {
    setSearchQuery(query);
    // Reset to page 0 when searching and load with search query
    loadUsers(0, query);
  };

  const handlePageChange = (page: number) => {
    loadUsers(page, searchQuery);
  };

  const handleAdd = () => {
    setEditingUser(null);
    setFormData({ uid: "", email: "", pwHash: "", roles: "ROLE_USER" });
    setDialogOpen(true);
  };

  const handleEdit = (row: User) => {
    setEditingUser(row);
    setFormData(row);
    setDialogOpen(true);
  };

  const handleSubmit = async () => {
    if (!formData.roles) {
      toast.error("Please fill in all required fields");
      return;
    }

    if (!editingUser && (!formData.email || !formData.pwHash)) {
      toast.error("Email and password are required for new users");
      return;
    }

    setIsSubmitting(true);
    try {
      if (editingUser) {
        await userAPI.update(editingUser.uid, {
          roles: formData.roles,
        });
        toast.success("User updated successfully");
      } else {
        await userAPI.create(formData);
        toast.success("User created successfully");
      }
      setDialogOpen(false);
      loadUsers(currentPage, searchQuery);
    } catch (error) {
      toast.error(
        `Failed to save user: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDeleteConfirm = async (row: User) => {
    await userAPI.delete(row.uid);
    loadUsers(currentPage, searchQuery);
  };

  const columns: ColumnDef<User>[] = [
    {
      accessorKey: "uid",
      header: "User ID",
    },
    {
      accessorKey: "name",
      header: "Name",
    },
    {
      accessorKey: "email",
      header: "Email",
    },
    {
      accessorKey: "roles",
      header: "Role",
    },
  ];

  return (
    <div>
      <DataTable
        columns={columns}
        data={users}
        isLoading={isLoading}
        onAdd={handleAdd}
        onEdit={handleEdit}
        onDeleteConfirm={handleDeleteConfirm}
        currentPage={currentPage}
        totalPages={totalPages}
        onPageChange={handlePageChange}
        onSearch={handleSearch}
        title="Users"
      />

      <FormDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        title={editingUser ? "Edit User" : "Add User"}
        description={
          editingUser ? "Update the user role" : "Create a new user"
        }
        onSubmit={handleSubmit}
        isSubmitting={isSubmitting}
      >
        <div className="space-y-4">
          <div className="grid gap-3">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              value={formData.email}
              onChange={(e) =>
                setFormData({ ...formData, email: e.target.value })
              }
              placeholder="e.g., user@example.com"
              disabled={!!editingUser}
            />
          </div>
          {!editingUser && (
            <div className="grid gap-3">
              <Label htmlFor="pwHash">Password Hash</Label>
              <Input
                id="pwHash"
                type="password"
                value={formData.pwHash}
                onChange={(e) =>
                  setFormData({ ...formData, pwHash: e.target.value })
                }
                placeholder="Enter password hash"
              />
            </div>
          )}
          <div className="grid gap-3">
            <Label htmlFor="roles">Role</Label>
            <Select
              value={formData.roles}
              onValueChange={(value) =>
                setFormData({ ...formData, roles: value })
              }
            >
              <SelectTrigger>
                <SelectValue placeholder="Select a role" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="ROLE_USER">User</SelectItem>
                <SelectItem value="ROLE_ADMIN">Admin</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </FormDialog>
    </div>
  );
}
