// Prisma seed script for countries table using WITS ISO3 country codes
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Complete WITS ISO3 country codes and names from CSV data
const countries = [
  { country_code: "ABW", name: "Aruba", numeric_code: "533" },
  { country_code: "AFG", name: "Afghanistan", numeric_code: "004" },
  { country_code: "AGO", name: "Angola", numeric_code: "024" },
  { country_code: "AIA", name: "Anguila", numeric_code: "660" },
  { country_code: "ALB", name: "Albania", numeric_code: "008" },
  { country_code: "AND", name: "Andorra", numeric_code: "020" },
  { country_code: "ANT", name: "Netherlands Antilles", numeric_code: "530" },
  { country_code: "ARE", name: "United Arab Emirates", numeric_code: "784" },
  { country_code: "ARG", name: "Argentina", numeric_code: "032" },
  { country_code: "ARM", name: "Armenia", numeric_code: "051" },
  { country_code: "ATG", name: "Antigua and Barbuda", numeric_code: "028" },
  { country_code: "AUS", name: "Australia", numeric_code: "036" },
  { country_code: "AUT", name: "Austria", numeric_code: "040" },
  { country_code: "AZE", name: "Azerbaijan", numeric_code: "031" },
  { country_code: "BDI", name: "Burundi", numeric_code: "108" },
  { country_code: "BEN", name: "Benin", numeric_code: "204" },
  { country_code: "BFA", name: "Burkina Faso", numeric_code: "854" },
  { country_code: "BGD", name: "Bangladesh", numeric_code: "050" },
  { country_code: "BGR", name: "Bulgaria", numeric_code: "100" },
  { country_code: "BHR", name: "Bahrain", numeric_code: "048" },
  { country_code: "BHS", name: "Bahamas, The", numeric_code: "044" },
  { country_code: "BIH", name: "Bosnia and Herzegovina", numeric_code: "070" },
  { country_code: "BLR", name: "Belarus", numeric_code: "112" },
  { country_code: "BLZ", name: "Belize", numeric_code: "084" },
  { country_code: "BMU", name: "Bermuda", numeric_code: "060" },
  { country_code: "BOL", name: "Bolivia", numeric_code: "068" },
  { country_code: "BRA", name: "Brazil", numeric_code: "076" },
  { country_code: "BRB", name: "Barbados", numeric_code: "052" },
  { country_code: "BRN", name: "Brunei", numeric_code: "096" },
  { country_code: "BTN", name: "Bhutan", numeric_code: "064" },
  { country_code: "BWA", name: "Botswana", numeric_code: "072" },
  {
    country_code: "CAF",
    name: "Central African Republic",
    numeric_code: "140",
  },
  { country_code: "CAN", name: "Canada", numeric_code: "124" },
  { country_code: "CHE", name: "Switzerland", numeric_code: "756" },
  { country_code: "CHL", name: "Chile", numeric_code: "152" },
  { country_code: "CHN", name: "China", numeric_code: "156" },
  { country_code: "CIV", name: "Cote d'Ivoire", numeric_code: "384" },
  { country_code: "CMR", name: "Cameroon", numeric_code: "120" },
  { country_code: "COG", name: "Congo, Rep.", numeric_code: "178" },
  { country_code: "COK", name: "Cook Islands", numeric_code: "184" },
  { country_code: "COL", name: "Colombia", numeric_code: "170" },
  { country_code: "COM", name: "Comoros", numeric_code: "174" },
  { country_code: "CPV", name: "Cape Verde", numeric_code: "132" },
  { country_code: "CRI", name: "Costa Rica", numeric_code: "188" },
  { country_code: "CSK", name: "Czechoslovakia", numeric_code: "200" },
  { country_code: "CUB", name: "Cuba", numeric_code: "192" },
  { country_code: "CYP", name: "Cyprus", numeric_code: "196" },
  { country_code: "CZE", name: "Czech Republic", numeric_code: "203" },
  { country_code: "DJI", name: "Djibouti", numeric_code: "262" },
  { country_code: "DMA", name: "Dominica", numeric_code: "212" },
  { country_code: "DOM", name: "Dominican Republic", numeric_code: "214" },
  { country_code: "DZA", name: "Algeria", numeric_code: "012" },
  { country_code: "ECU", name: "Ecuador", numeric_code: "218" },
  { country_code: "EGY", name: "Egypt, Arab Rep.", numeric_code: "818" },
  { country_code: "ERI", name: "Eritrea", numeric_code: "232" },
  { country_code: "EST", name: "Estonia", numeric_code: "233" },
  {
    country_code: "ETH",
    name: "Ethiopia(excludes Eritrea)",
    numeric_code: "231",
  },
  { country_code: "EUN", name: "European Union", numeric_code: "918" },
  { country_code: "FIN", name: "Finland", numeric_code: "246" },
  { country_code: "FJI", name: "Fiji", numeric_code: "242" },
  { country_code: "FRO", name: "Faeroe Islands", numeric_code: "234" },
  { country_code: "GAB", name: "Gabon", numeric_code: "266" },
  { country_code: "GAZ", name: "Gaza Strip", numeric_code: "274" },
  { country_code: "GBR", name: "United Kingdom", numeric_code: "826" },
  { country_code: "GEO", name: "Georgia", numeric_code: "268" },
  { country_code: "GHA", name: "Ghana", numeric_code: "288" },
  { country_code: "GIN", name: "Guinea", numeric_code: "324" },
  { country_code: "GMB", name: "Gambia, The", numeric_code: "270" },
  { country_code: "GNB", name: "Guinea-Bissau", numeric_code: "624" },
  { country_code: "GNQ", name: "Equatorial Guinea", numeric_code: "226" },
  { country_code: "GRD", name: "Grenada", numeric_code: "308" },
  { country_code: "GRL", name: "Greenland", numeric_code: "304" },
  { country_code: "GTM", name: "Guatemala", numeric_code: "320" },
  { country_code: "GUF", name: "French Guiana", numeric_code: "254" },
  { country_code: "GUY", name: "Guyana", numeric_code: "328" },
  { country_code: "HKG", name: "Hong Kong, China", numeric_code: "344" },
  { country_code: "HND", name: "Honduras", numeric_code: "340" },
  { country_code: "HRV", name: "Croatia", numeric_code: "191" },
  { country_code: "HTI", name: "Haiti", numeric_code: "332" },
  { country_code: "HUN", name: "Hungary", numeric_code: "348" },
  { country_code: "IDN", name: "Indonesia", numeric_code: "360" },
  { country_code: "IND", name: "India", numeric_code: "356" },
  { country_code: "IRN", name: "Iran, Islamic Rep.", numeric_code: "364" },
  { country_code: "IRQ", name: "Iraq", numeric_code: "368" },
  { country_code: "ISL", name: "Iceland", numeric_code: "352" },
  { country_code: "ISR", name: "Israel", numeric_code: "376" },
  { country_code: "JAM", name: "Jamaica", numeric_code: "388" },
  { country_code: "JOR", name: "Jordan", numeric_code: "400" },
  { country_code: "JPN", name: "Japan", numeric_code: "392" },
  { country_code: "KAZ", name: "Kazakhstan", numeric_code: "398" },
  { country_code: "KEN", name: "Kenya", numeric_code: "404" },
  { country_code: "KGZ", name: "Kyrgyz Republic", numeric_code: "417" },
  { country_code: "KHM", name: "Cambodia", numeric_code: "116" },
  { country_code: "KNA", name: "St. Kitts and Nevis", numeric_code: "659" },
  { country_code: "KOR", name: "Korea, Rep.", numeric_code: "410" },
  { country_code: "KWT", name: "Kuwait", numeric_code: "414" },
  { country_code: "LAO", name: "Lao PDR", numeric_code: "418" },
  { country_code: "LBN", name: "Lebanon", numeric_code: "422" },
  { country_code: "LBR", name: "Liberia", numeric_code: "430" },
  { country_code: "LBY", name: "Libya", numeric_code: "434" },
  { country_code: "LCA", name: "St. Lucia", numeric_code: "662" },
  { country_code: "LIE", name: "Liechtenstein", numeric_code: "438" },
  { country_code: "LKA", name: "Sri Lanka", numeric_code: "144" },
  { country_code: "LSO", name: "Lesotho", numeric_code: "426" },
  { country_code: "LTU", name: "Lithuania", numeric_code: "440" },
  { country_code: "LVA", name: "Latvia", numeric_code: "428" },
  { country_code: "MAC", name: "Macao", numeric_code: "446" },
  { country_code: "MAR", name: "Morocco", numeric_code: "504" },
  { country_code: "MDA", name: "Moldova", numeric_code: "498" },
  { country_code: "MDG", name: "Madagascar", numeric_code: "450" },
  { country_code: "MDV", name: "Maldives", numeric_code: "462" },
  { country_code: "MEX", name: "Mexico", numeric_code: "484" },
  { country_code: "MKD", name: "Macedonia, FYR", numeric_code: "807" },
  { country_code: "MLI", name: "Mali", numeric_code: "466" },
  { country_code: "MLT", name: "Malta", numeric_code: "470" },
  { country_code: "MMR", name: "Myanmar", numeric_code: "104" },
  { country_code: "MNG", name: "Mongolia", numeric_code: "496" },
  { country_code: "MNT", name: "Montenegro", numeric_code: "499" },
  { country_code: "MOZ", name: "Mozambique", numeric_code: "508" },
  { country_code: "MRT", name: "Mauritania", numeric_code: "478" },
  { country_code: "MSR", name: "Montserrat", numeric_code: "500" },
  { country_code: "MUS", name: "Mauritius", numeric_code: "480" },
  { country_code: "MWI", name: "Malawi", numeric_code: "454" },
  { country_code: "MYS", name: "Malaysia", numeric_code: "458" },
  { country_code: "MYT", name: "Mayotte", numeric_code: "175" },
  { country_code: "NAM", name: "Namibia", numeric_code: "516" },
  { country_code: "NER", name: "Niger", numeric_code: "562" },
  { country_code: "NGA", name: "Nigeria", numeric_code: "566" },
  { country_code: "NIC", name: "Nicaragua", numeric_code: "558" },
  { country_code: "NOR", name: "Norway", numeric_code: "578" },
  { country_code: "NPL", name: "Nepal", numeric_code: "524" },
  { country_code: "NRU", name: "Nauru", numeric_code: "520" },
  { country_code: "NZL", name: "New Zealand", numeric_code: "554" },
  { country_code: "OMN", name: "Oman", numeric_code: "512" },
  { country_code: "PAK", name: "Pakistan", numeric_code: "586" },
  { country_code: "PAN", name: "Panama", numeric_code: "591" },
  { country_code: "PER", name: "Peru", numeric_code: "604" },
  { country_code: "PHL", name: "Philippines", numeric_code: "608" },
  { country_code: "PLW", name: "Palau", numeric_code: "585" },
  { country_code: "PNG", name: "Papua New Guinea", numeric_code: "598" },
  { country_code: "POL", name: "Poland", numeric_code: "616" },
  { country_code: "PRK", name: "Korea, Dem. Rep.", numeric_code: "408" },
  { country_code: "PRT", name: "Portugal", numeric_code: "620" },
  { country_code: "PRY", name: "Paraguay", numeric_code: "600" },
  { country_code: "PSE", name: "Occ.Pal.Terr", numeric_code: "275" },
  { country_code: "PYF", name: "French Polynesia", numeric_code: "258" },
  { country_code: "QAT", name: "Qatar", numeric_code: "634" },
  { country_code: "ROM", name: "Romania", numeric_code: "642" },
  { country_code: "RUS", name: "Russian Federation", numeric_code: "643" },
  { country_code: "RWA", name: "Rwanda", numeric_code: "646" },
  { country_code: "SAU", name: "Saudi Arabia", numeric_code: "682" },
  { country_code: "SDN", name: "Fm Sudan", numeric_code: "736" },
  { country_code: "SEN", name: "Senegal", numeric_code: "686" },
  {
    country_code: "SER",
    name: "Serbia, FR(Serbia/Montenegro)",
    numeric_code: "891",
  },
  { country_code: "SGP", name: "Singapore", numeric_code: "702" },
  { country_code: "SLB", name: "Solomon Islands", numeric_code: "090" },
  { country_code: "SLE", name: "Sierra Leone", numeric_code: "694" },
  { country_code: "SLV", name: "El Salvador", numeric_code: "222" },
  { country_code: "SMR", name: "San Marino", numeric_code: "674" },
  { country_code: "STP", name: "Sao Tome and Principe", numeric_code: "678" },
  { country_code: "SUD", name: "Sudan", numeric_code: "729" },
  { country_code: "SUR", name: "Suriname", numeric_code: "740" },
  { country_code: "SVK", name: "Slovak Republic", numeric_code: "703" },
  { country_code: "SVN", name: "Slovenia", numeric_code: "705" },
  { country_code: "SWE", name: "Sweden", numeric_code: "752" },
  { country_code: "SWZ", name: "Swaziland", numeric_code: "748" },
  { country_code: "SYC", name: "Seychelles", numeric_code: "690" },
  { country_code: "SYR", name: "Syrian Arab Republic", numeric_code: "760" },
  { country_code: "TCD", name: "Chad", numeric_code: "148" },
  { country_code: "TGO", name: "Togo", numeric_code: "768" },
  { country_code: "THA", name: "Thailand", numeric_code: "764" },
  { country_code: "TJK", name: "Tajikistan", numeric_code: "762" },
  { country_code: "TKM", name: "Turkmenistan", numeric_code: "795" },
  { country_code: "TMP", name: "East Timor", numeric_code: "626" },
  { country_code: "TON", name: "Tonga", numeric_code: "776" },
  { country_code: "TTO", name: "Trinidad and Tobago", numeric_code: "780" },
  { country_code: "TUN", name: "Tunisia", numeric_code: "788" },
  { country_code: "TUR", name: "Turkey", numeric_code: "792" },
  { country_code: "TUV", name: "Tuvalu", numeric_code: "798" },
  { country_code: "TWN", name: "Taiwan, China", numeric_code: "158" },
  { country_code: "TZA", name: "Tanzania", numeric_code: "834" },
  { country_code: "UGA", name: "Uganda", numeric_code: "800" },
  { country_code: "UKR", name: "Ukraine", numeric_code: "804" },
  { country_code: "UNS", name: "Unspecified", numeric_code: "898" },
  { country_code: "URY", name: "Uruguay", numeric_code: "858" },
  { country_code: "USA", name: "United States", numeric_code: "840" },
  { country_code: "UZB", name: "Uzbekistan", numeric_code: "860" },
  {
    country_code: "VCT",
    name: "St. Vincent and the Grenadines",
    numeric_code: "670",
  },
  { country_code: "VEN", name: "Venezuela", numeric_code: "862" },
  { country_code: "VNM", name: "Vietnam", numeric_code: "704" },
  { country_code: "VUT", name: "Vanuatu", numeric_code: "548" },
  { country_code: "WSM", name: "Samoa", numeric_code: "882" },
  { country_code: "YEM", name: "Yemen", numeric_code: "887" },
  {
    country_code: "YUG",
    name: "Yugoslavia, FR (Serbia/Montenegro)",
    numeric_code: "890",
  },
  { country_code: "ZAF", name: "South Africa", numeric_code: "710" },
  { country_code: "ZAR", name: "Congo, Dem. Rep.", numeric_code: "180" },
  { country_code: "ZMB", name: "Zambia", numeric_code: "894" },
  { country_code: "ZWE", name: "Zimbabwe", numeric_code: "716" },
];

async function main() {
  for (const country of countries) {
    await prisma.country.upsert({
      where: { country_code: country.country_code },
      update: { name: country.name, numeric_code: country.numeric_code },
      create: {
        country_code: country.country_code,
        name: country.name,
        numeric_code: country.numeric_code,
      },
    });
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
