// Prisma seed script for countries table using WITS ISO3 country codes
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// WITS ISO3 country codes and names (sample, replace with full list as needed)
const countries = [
  { iso_code: "AFG", name: "Afghanistan" },
  { iso_code: "ALB", name: "Albania" },
  { iso_code: "DZA", name: "Algeria" },
  { iso_code: "AND", name: "Andorra" },
  { iso_code: "AGO", name: "Angola" },
  { iso_code: "ATG", name: "Antigua and Barbuda" },
  { iso_code: "ARG", name: "Argentina" },
  { iso_code: "ARM", name: "Armenia" },
  { iso_code: "AUS", name: "Australia" },
  { iso_code: "AUT", name: "Austria" },
  { iso_code: "AZE", name: "Azerbaijan" },
  { iso_code: "BHS", name: "Bahamas" },
  { iso_code: "BHR", name: "Bahrain" },
  { iso_code: "BGD", name: "Bangladesh" },
  { iso_code: "BRB", name: "Barbados" },
  { iso_code: "BLR", name: "Belarus" },
  { iso_code: "BEL", name: "Belgium" },
  { iso_code: "BLZ", name: "Belize" },
  { iso_code: "BEN", name: "Benin" },
  { iso_code: "BTN", name: "Bhutan" },
  { iso_code: "BOL", name: "Bolivia" },
  { iso_code: "BIH", name: "Bosnia and Herzegovina" },
  { iso_code: "BWA", name: "Botswana" },
  { iso_code: "BRA", name: "Brazil" },
  { iso_code: "BRN", name: "Brunei Darussalam" },
  { iso_code: "BGR", name: "Bulgaria" },
  { iso_code: "BFA", name: "Burkina Faso" },
  { iso_code: "BDI", name: "Burundi" },
  { iso_code: "KHM", name: "Cambodia" },
  { iso_code: "CMR", name: "Cameroon" },
  { iso_code: "CAN", name: "Canada" },
  { iso_code: "CPV", name: "Cape Verde" },
  { iso_code: "CAF", name: "Central African Republic" },
  { iso_code: "TCD", name: "Chad" },
  { iso_code: "CHL", name: "Chile" },
  { iso_code: "CHN", name: "China" },
  { iso_code: "COL", name: "Colombia" },
  { iso_code: "COM", name: "Comoros" },
  { iso_code: "COG", name: "Congo" },
  { iso_code: "COD", name: "Congo, Dem. Rep." },
  { iso_code: "CRI", name: "Costa Rica" },
  { iso_code: "CIV", name: "Côte d'Ivoire" },
  { iso_code: "HRV", name: "Croatia" },
  { iso_code: "CUB", name: "Cuba" },
  { iso_code: "CYP", name: "Cyprus" },
  { iso_code: "CZE", name: "Czech Republic" },
  { iso_code: "DNK", name: "Denmark" },
  { iso_code: "DJI", name: "Djibouti" },
  { iso_code: "DMA", name: "Dominica" },
  { iso_code: "DOM", name: "Dominican Republic" },
  { iso_code: "ECU", name: "Ecuador" },
  { iso_code: "EGY", name: "Egypt" },
  { iso_code: "SLV", name: "El Salvador" },
  { iso_code: "GNQ", name: "Equatorial Guinea" },
  { iso_code: "ERI", name: "Eritrea" },
  { iso_code: "EST", name: "Estonia" },
  { iso_code: "SWZ", name: "Eswatini" },
  { iso_code: "ETH", name: "Ethiopia" },
  { iso_code: "FJI", name: "Fiji" },
  { iso_code: "FIN", name: "Finland" },
  { iso_code: "FRA", name: "France" },
  { iso_code: "GAB", name: "Gabon" },
  { iso_code: "GMB", name: "Gambia" },
  { iso_code: "GEO", name: "Georgia" },
  { iso_code: "DEU", name: "Germany" },
  { iso_code: "GHA", name: "Ghana" },
  { iso_code: "GRC", name: "Greece" },
  { iso_code: "GRD", name: "Grenada" },
  { iso_code: "GTM", name: "Guatemala" },
  { iso_code: "GIN", name: "Guinea" },
  { iso_code: "GNB", name: "Guinea-Bissau" },
  { iso_code: "GUY", name: "Guyana" },
  { iso_code: "HTI", name: "Haiti" },
  { iso_code: "HND", name: "Honduras" },
  { iso_code: "HUN", name: "Hungary" },
  { iso_code: "ISL", name: "Iceland" },
  { iso_code: "IND", name: "India" },
  { iso_code: "IDN", name: "Indonesia" },
  { iso_code: "IRN", name: "Iran" },
  { iso_code: "IRQ", name: "Iraq" },
  { iso_code: "IRL", name: "Ireland" },
  { iso_code: "ISR", name: "Israel" },
  { iso_code: "ITA", name: "Italy" },
  { iso_code: "JAM", name: "Jamaica" },
  { iso_code: "JPN", name: "Japan" },
  { iso_code: "JOR", name: "Jordan" },
  { iso_code: "KAZ", name: "Kazakhstan" },
  { iso_code: "KEN", name: "Kenya" },
  { iso_code: "KIR", name: "Kiribati" },
  { iso_code: "KOR", name: "Korea, Rep." },
  { iso_code: "KWT", name: "Kuwait" },
  { iso_code: "KGZ", name: "Kyrgyz Republic" },
  { iso_code: "LAO", name: "Lao PDR" },
  { iso_code: "LVA", name: "Latvia" },
  { iso_code: "LBN", name: "Lebanon" },
  { iso_code: "LSO", name: "Lesotho" },
  { iso_code: "LBR", name: "Liberia" },
  { iso_code: "LBY", name: "Libya" },
  { iso_code: "LIE", name: "Liechtenstein" },
  { iso_code: "LTU", name: "Lithuania" },
  { iso_code: "LUX", name: "Luxembourg" },
  { iso_code: "MDG", name: "Madagascar" },
  { iso_code: "MWI", name: "Malawi" },
  { iso_code: "MYS", name: "Malaysia" },
  { iso_code: "MDV", name: "Maldives" },
  { iso_code: "MLI", name: "Mali" },
  { iso_code: "MLT", name: "Malta" },
  { iso_code: "MHL", name: "Marshall Islands" },
  { iso_code: "MRT", name: "Mauritania" },
  { iso_code: "MUS", name: "Mauritius" },
  { iso_code: "MEX", name: "Mexico" },
  { iso_code: "FSM", name: "Micronesia, Fed. Sts." },
  { iso_code: "MDA", name: "Moldova" },
  { iso_code: "MCO", name: "Monaco" },
  { iso_code: "MNG", name: "Mongolia" },
  { iso_code: "MNE", name: "Montenegro" },
  { iso_code: "MAR", name: "Morocco" },
  { iso_code: "MOZ", name: "Mozambique" },
  { iso_code: "MMR", name: "Myanmar" },
  { iso_code: "NAM", name: "Namibia" },
  { iso_code: "NRU", name: "Nauru" },
  { iso_code: "NPL", name: "Nepal" },
  { iso_code: "NLD", name: "Netherlands" },
  { iso_code: "NZL", name: "New Zealand" },
  { iso_code: "NIC", name: "Nicaragua" },
  { iso_code: "NER", name: "Niger" },
  { iso_code: "NGA", name: "Nigeria" },
  { iso_code: "MKD", name: "North Macedonia" },
  { iso_code: "NOR", name: "Norway" },
  { iso_code: "OMN", name: "Oman" },
  { iso_code: "PAK", name: "Pakistan" },
  { iso_code: "PLW", name: "Palau" },
  { iso_code: "PSE", name: "Palestine" },
  { iso_code: "PAN", name: "Panama" },
  { iso_code: "PNG", name: "Papua New Guinea" },
  { iso_code: "PRY", name: "Paraguay" },
  { iso_code: "PER", name: "Peru" },
  { iso_code: "PHL", name: "Philippines" },
  { iso_code: "POL", name: "Poland" },
  { iso_code: "PRT", name: "Portugal" },
  { iso_code: "QAT", name: "Qatar" },
  { iso_code: "ROU", name: "Romania" },
  { iso_code: "RUS", name: "Russian Federation" },
  { iso_code: "RWA", name: "Rwanda" },
  { iso_code: "KNA", name: "Saint Kitts and Nevis" },
  { iso_code: "LCA", name: "Saint Lucia" },
  { iso_code: "VCT", name: "Saint Vincent and the Grenadines" },
  { iso_code: "WSM", name: "Samoa" },
  { iso_code: "SMR", name: "San Marino" },
  { iso_code: "STP", name: "Sao Tome and Principe" },
  { iso_code: "SAU", name: "Saudi Arabia" },
  { iso_code: "SEN", name: "Senegal" },
  { iso_code: "SRB", name: "Serbia" },
  { iso_code: "SYC", name: "Seychelles" },
  { iso_code: "SLE", name: "Sierra Leone" },
  { iso_code: "SGP", name: "Singapore" },
  { iso_code: "SVK", name: "Slovak Republic" },
  { iso_code: "SVN", name: "Slovenia" },
  { iso_code: "SLB", name: "Solomon Islands" },
  { iso_code: "SOM", name: "Somalia" },
  { iso_code: "ZAF", name: "South Africa" },
  { iso_code: "SSD", name: "South Sudan" },
  { iso_code: "ESP", name: "Spain" },
  { iso_code: "LKA", name: "Sri Lanka" },
  { iso_code: "SDN", name: "Sudan" },
  { iso_code: "SUR", name: "Suriname" },
  { iso_code: "SWE", name: "Sweden" },
  { iso_code: "CHE", name: "Switzerland" },
  { iso_code: "SYR", name: "Syrian Arab Republic" },
  { iso_code: "TWN", name: "Taiwan" },
  { iso_code: "TJK", name: "Tajikistan" },
  { iso_code: "TZA", name: "Tanzania" },
  { iso_code: "THA", name: "Thailand" },
  { iso_code: "TLS", name: "Timor-Leste" },
  { iso_code: "TGO", name: "Togo" },
  { iso_code: "TON", name: "Tonga" },
  { iso_code: "TTO", name: "Trinidad and Tobago" },
  { iso_code: "TUN", name: "Tunisia" },
  { iso_code: "TUR", name: "Turkey" },
  { iso_code: "TKM", name: "Turkmenistan" },
  { iso_code: "TUV", name: "Tuvalu" },
  { iso_code: "UGA", name: "Uganda" },
  { iso_code: "UKR", name: "Ukraine" },
  { iso_code: "ARE", name: "United Arab Emirates" },
  { iso_code: "GBR", name: "United Kingdom" },
  { iso_code: "USA", name: "United States" },
  { iso_code: "URY", name: "Uruguay" },
  { iso_code: "UZB", name: "Uzbekistan" },
  { iso_code: "VUT", name: "Vanuatu" },
  { iso_code: "VEN", name: "Venezuela" },
  { iso_code: "VNM", name: "Vietnam" },
  { iso_code: "YEM", name: "Yemen" },
  { iso_code: "ZMB", name: "Zambia" },
  { iso_code: "ZWE", name: "Zimbabwe" },
];

async function main() {
  for (const country of countries) {
    await prisma.countries.upsert({
      where: { iso_code: country.iso_code },
      update: { name: country.name },
      create: { iso_code: country.iso_code, name: country.name },
    });
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
